ARG golang_image
ARG base_image

FROM ${golang_image} AS builder
WORKDIR /tmp
RUN mkdir -p /tmp/workspace && chmod 0777 /tmp/workspace
WORKDIR /tmp/workspace
ENV GO111MODULE=on GOPROXY=direct CGO_ENABLED=1 GOFIPS140=certified GO_BUILD_TAGS=strictfipsruntime,no_openssl GOFLAGS=-buildvcs=false
COPY . ./
RUN make build-metrics

FROM ${base_image}
RUN microdnf install -y ca-certificates openssl-libs \
    && microdnf clean all
ENV GODEBUG=fips140=auto
COPY ./misc/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
WORKDIR /app
COPY --from=builder /tmp/workspace/cni-metrics-helper /app/
ENTRYPOINT ["/app/cni-metrics-helper", "--cloudwatch=false"]
