ARG golang_image
ARG base_image

FROM ${golang_image} AS builder
WORKDIR /go/src/github.com/aws/amazon-vpc-cni-k8s
ENV GO111MODULE=on GOPROXY=direct CGO_ENABLED=1
COPY . ./
RUN make plugins && make debug-script && make build-aws-vpc-cni-init

FROM ${base_image}
RUN microdnf install -y ca-certificates iproute iptables openssl-libs util-linux-core \
    && microdnf clean all
WORKDIR /init
COPY --from=builder /go/src/github.com/aws/amazon-vpc-cni-k8s/core-plugins/ \
    /go/src/github.com/aws/amazon-vpc-cni-k8s/aws-cni-support.sh \
    /go/src/github.com/aws/amazon-vpc-cni-k8s/aws-vpc-cni-init /init/
CMD ["/init/aws-vpc-cni-init"]
