ARG golang_image
ARG base_image

FROM ${golang_image} AS builder
WORKDIR /go/src/github.com/aws/amazon-vpc-cni-k8s
ENV GO111MODULE=on GOPROXY=direct CGO_ENABLED=1
COPY . ./
RUN make build-metrics

FROM ${base_image}
RUN microdnf install -y ca-certificates openssl-libs \
    && microdnf clean all
COPY ./misc/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
WORKDIR /app
COPY --from=builder /go/src/github.com/aws/amazon-vpc-cni-k8s/cni-metrics-helper /app/
ENTRYPOINT ["/app/cni-metrics-helper", "--cloudwatch=false"]
