ARG golang_image
ARG base_image

FROM ${golang_image} AS builder
WORKDIR /tmp
RUN mkdir -p /tmp/workspace && chmod 0777 /tmp/workspace
WORKDIR /tmp/workspace
ENV GO111MODULE=on GOPROXY=direct CGO_ENABLED=1 GOFIPS140=certified GO_BUILD_TAGS=strictfipsruntime,no_openssl GOFLAGS=-buildvcs=false
COPY . ./
RUN make plugins && make debug-script && make build-aws-vpc-cni-init

FROM ${base_image}
RUN microdnf install -y ca-certificates iproute iptables openssl-libs util-linux-core \
    && microdnf clean all
ENV GODEBUG=fips140=auto
WORKDIR /init
COPY --from=builder /tmp/workspace/core-plugins/ \
    /tmp/workspace/aws-cni-support.sh \
    /tmp/workspace/aws-vpc-cni-init /init/
CMD ["/init/aws-vpc-cni-init"]
